productName: Ruok-tester
webEndpoints:
- https://www.lipsum.com
githubEndpoints:
- https://github.com/PHACDataHub/ruok-service-autochecker
- https://github.com/PHACDataHub/phac-bots
- https://github.com/PHACDataHub/statscan-phac-diffpriv-collab
- https://github.com/PHACDataHub/phacronyms
